{
  "hash": "977d9923eb55347a46ef0e75cf72d0fd",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"1. Data Quality Assessment\"\n---\n\n## Assessment approach\n\nBefore running any analysis, we systematically assessed the quality of each dataset along several dimensions. The table below summarizes the checks applied to each file.\n\n| Check | Description |\n|---|---|\n| **File overview** | Row and column counts; identification of structurally empty columns |\n| **Missing values** | Missing rate per variable, grouped by thematic block; flagging variables with meaningful missingness |\n| **Duplicates** | Check for duplicate student or record identifiers |\n| **Survey response quality** | Completion rate (`progress`) and response duration (`duration_min`) outliers |\n| **Range validity** | Expected value ranges for all variables (Likert scales, binary indicators, continuous measures) |\n| **Scale consistency** | Replication of pre-computed scale averages from constituent items; reversal checks for reverse-coded items |\n| **Derived variable consistency** | Cross-variable logical checks (e.g., `educ_parent_max` vs. `educ_mother`/`educ_father`; math score totals vs. item sums) |\n\nAdditional dataset-specific checks are described within each section below. Thresholds were set on substantive grounds based on the study codebook and instrument documentation.\n\n::: {#77b9e526 .cell execution_count=1}\n``` {.python .cell-code}\nimport sys\nsys.path.insert(0, \"../src\")\nimport utils\nimport checks\n\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\nutils.set_theme()\n\ndfs = utils.load_all()\nbaseline  = dfs[\"baseline\"]\nschools   = dfs[\"schools\"]\nmath_chat = dfs[\"math_chat\"]\nmath_quiz = dfs[\"math_quiz\"]\nvoc_chat  = dfs[\"voc_chat\"]\nvoc_steps = dfs[\"voc_steps\"]\n```\n:::\n\n\n---\n\n## Data sources\n\nThe study draws on seven datasets from two sources: a Qualtrics baseline survey and interaction logs from the uDocz educational platform.\n\n| Dataset | Grain | Description |\n|---|---|---|\n| `baseline_estudiantes` | Student | Pre-treatment survey covering demographics, psychological scales, math assessment, and post-secondary aspirations |\n| `randomizacion_escuelas` | School | School-level treatment assignment and stratification variables used for randomization |\n| `math_chat_casa` | Message | Student–AI math tutoring conversations conducted at home |\n| `math_chat_escuela` | Message | Student–AI math tutoring conversations conducted at school, with topic and correctness data |\n| `math_ponte_prueba` | Quiz attempt | Math quiz interactions from the platform, with correctness indicators |\n| `voc_chat` | Message | Student–AI career guidance conversations across an 8-step vocational journey |\n| `voc_steps` | Student × step | Student-level progress, time spent, and completion across the 8 vocational journey steps |\n\n---\n\n## Student Baseline Data: Survey and Test\n\n### A. File overview\n\nRow and column counts; identification of structurally empty columns (conditional free-text fields never filled in).\n\n::: {#1efb6ee9 .cell execution_count=2}\n``` {.python .cell-code}\nprint(f\"Rows: {len(baseline):,}  |  Columns: {len(baseline.columns)}\")\n\nempty_cols = checks.check_column_empty(baseline)\nprint(f\"\\nStructurally empty columns ({len(empty_cols)}):\")\nprint(empty_cols[[\"variable\"]].to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 1,203  |  Columns: 168\n\nStructurally empty columns (2):\n           variable\ncareer_first_choice\n     action_3months\n```\n:::\n:::\n\n\n::: {.callout-note}\nThe public dataset contains 1,203 students and 168 variables (183 in the raw data; 15 dropped during anonymization to remove personally identifiable information). Two variables are structurally empty (100% missing): `career_first_choice` and `action_3months`. Both are conditional free-text fields that were never filled in, likely because survey skip logic routed most respondents away from them. They are excluded from all subsequent checks.\n:::\n\n::: {#fe441954 .cell execution_count=3}\n``` {.python .cell-code}\nbaseline = baseline.drop(columns=empty_cols[\"variable\"].tolist())\n```\n:::\n\n\n### B. Missing values\n\nMissing rate per variable, grouped by thematic block. Structurally empty columns excluded.\n\n::: {#03e86d80 .cell execution_count=4}\n``` {.python .cell-code}\nmissing_results = pd.concat([\n    checks.check_missing(baseline, cols=[c for c in cols if c in baseline.columns],\n                         group_label=block)\n    for block, cols in utils.BASELINE_VARS.items()\n], ignore_index=True)\n\ntotal_vars = sum(len(cols) for cols in utils.BASELINE_VARS.values())\nvars_with_missing = len(missing_results)\nprint(f\"{vars_with_missing} of {total_vars} variables have at least one missing value.\")\n\nutils.gt_missing(missing_results, title=\"Variables with missing values — Baseline survey\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n6 of 162 variables have at least one missing value.\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div id=\"uhbsrcuqth\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#uhbsrcuqth table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#uhbsrcuqth thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#uhbsrcuqth p { margin: 0; padding: 0; }\n #uhbsrcuqth .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 16px; font-weight: normal; font-style: normal; background-color: #FFFFFF; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #uhbsrcuqth .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #uhbsrcuqth .gt_title { color: #333333; font-size: 125%; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: #FFFFFF; border-bottom-width: 0; }\n #uhbsrcuqth .gt_subtitle { color: #333333; font-size: 85%; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: #FFFFFF; border-top-width: 0; }\n #uhbsrcuqth .gt_heading { background-color: #FFFFFF; text-align: center; border-bottom-color: #FFFFFF; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #uhbsrcuqth .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #uhbsrcuqth .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #uhbsrcuqth .gt_col_heading { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #uhbsrcuqth .gt_column_spanner_outer { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #uhbsrcuqth .gt_column_spanner_outer:first-child { padding-left: 0; }\n #uhbsrcuqth .gt_column_spanner_outer:last-child { padding-right: 0; }\n #uhbsrcuqth .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #uhbsrcuqth .gt_spanner_row { border-bottom-style: hidden; }\n #uhbsrcuqth .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #uhbsrcuqth .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #uhbsrcuqth .gt_from_md> :first-child { margin-top: 0; }\n #uhbsrcuqth .gt_from_md> :last-child { margin-bottom: 0; }\n #uhbsrcuqth .gt_row { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #uhbsrcuqth .gt_stub { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #uhbsrcuqth .gt_stub_row_group { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #uhbsrcuqth .gt_row_group_first td { border-top-width: 2px; }\n #uhbsrcuqth .gt_row_group_first th { border-top-width: 2px; }\n #uhbsrcuqth .gt_striped { color: #333333; background-color: #F4F4F4; }\n #uhbsrcuqth .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #uhbsrcuqth .gt_grand_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #uhbsrcuqth .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #uhbsrcuqth .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #uhbsrcuqth .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #uhbsrcuqth .gt_sourcenote { font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #uhbsrcuqth .gt_left { text-align: left; }\n #uhbsrcuqth .gt_center { text-align: center; }\n #uhbsrcuqth .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #uhbsrcuqth .gt_font_normal { font-weight: normal; }\n #uhbsrcuqth .gt_font_bold { font-weight: bold; }\n #uhbsrcuqth .gt_font_italic { font-style: italic; }\n #uhbsrcuqth .gt_super { font-size: 65%; }\n #uhbsrcuqth .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #uhbsrcuqth .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\" style=\"font-weight: bold;\">Variables with missing values — Baseline survey</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"group\">Dimension</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">Variable</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_missing\">N Missing</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pct_missing\">% Missing</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td style=\"border-top: 2px solid #333333;\" class=\"gt_row gt_left\">Demographics</td>\n    <td style=\"border-top: 2px solid #333333;\" class=\"gt_row gt_left\">educ_father</td>\n    <td style=\"border-top: 2px solid #333333;\" class=\"gt_row gt_right\">102</td>\n    <td style=\"border-top: 2px solid #333333;\" class=\"gt_row gt_right\">8.5</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Demographics</td>\n    <td class=\"gt_row gt_left\">age_cat</td>\n    <td class=\"gt_row gt_right\">48</td>\n    <td class=\"gt_row gt_right\">4.0</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Demographics</td>\n    <td class=\"gt_row gt_left\">age</td>\n    <td class=\"gt_row gt_right\">48</td>\n    <td class=\"gt_row gt_right\">4.0</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Labor market beliefs</td>\n    <td class=\"gt_row gt_left\">salary_university</td>\n    <td class=\"gt_row gt_right\">192</td>\n    <td class=\"gt_row gt_right\">16.0</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Labor market beliefs</td>\n    <td class=\"gt_row gt_left\">salary_technical</td>\n    <td class=\"gt_row gt_right\">187</td>\n    <td class=\"gt_row gt_right\">15.5</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Labor market beliefs</td>\n    <td class=\"gt_row gt_left\">salary_secondary</td>\n    <td class=\"gt_row gt_right\">164</td>\n    <td class=\"gt_row gt_right\">13.6</td>\n  </tr>\n</tbody>\n\n\n</table>\n\n</div>\n        \n```\n:::\n:::\n\n\n::: {.callout-note}\nOnly 6 of 162 variables have missing values. Missing rates are low across the board: `educ_father` (8.5%) and `age`/`age_cat` (4.0%, same students) in the demographics block; and the three salary expectation variables (13.6%–16.0%) in the labor market beliefs block, reflecting students who skipped that module. All other variables are fully observed.\n:::\n\n### C. Duplicates\n\n::: {#3c15ea98 .cell execution_count=5}\n``` {.python .cell-code}\ndup_results = checks.check_duplicates(baseline, \"qualtrics_id\")\nutils.gt_check_results(dup_results, title=\"Duplicate check — qualtrics_id\")\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div id=\"hzntalxwue\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#hzntalxwue table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#hzntalxwue thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#hzntalxwue p { margin: 0; padding: 0; }\n #hzntalxwue .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 16px; font-weight: normal; font-style: normal; background-color: #FFFFFF; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #hzntalxwue .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #hzntalxwue .gt_title { color: #333333; font-size: 125%; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: #FFFFFF; border-bottom-width: 0; }\n #hzntalxwue .gt_subtitle { color: #333333; font-size: 85%; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: #FFFFFF; border-top-width: 0; }\n #hzntalxwue .gt_heading { background-color: #FFFFFF; text-align: center; border-bottom-color: #FFFFFF; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #hzntalxwue .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #hzntalxwue .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #hzntalxwue .gt_col_heading { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #hzntalxwue .gt_column_spanner_outer { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #hzntalxwue .gt_column_spanner_outer:first-child { padding-left: 0; }\n #hzntalxwue .gt_column_spanner_outer:last-child { padding-right: 0; }\n #hzntalxwue .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #hzntalxwue .gt_spanner_row { border-bottom-style: hidden; }\n #hzntalxwue .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #hzntalxwue .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #hzntalxwue .gt_from_md> :first-child { margin-top: 0; }\n #hzntalxwue .gt_from_md> :last-child { margin-bottom: 0; }\n #hzntalxwue .gt_row { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #hzntalxwue .gt_stub { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #hzntalxwue .gt_stub_row_group { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #hzntalxwue .gt_row_group_first td { border-top-width: 2px; }\n #hzntalxwue .gt_row_group_first th { border-top-width: 2px; }\n #hzntalxwue .gt_striped { color: #333333; background-color: #F4F4F4; }\n #hzntalxwue .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #hzntalxwue .gt_grand_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #hzntalxwue .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #hzntalxwue .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #hzntalxwue .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #hzntalxwue .gt_sourcenote { font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #hzntalxwue .gt_left { text-align: left; }\n #hzntalxwue .gt_center { text-align: center; }\n #hzntalxwue .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #hzntalxwue .gt_font_normal { font-weight: normal; }\n #hzntalxwue .gt_font_bold { font-weight: bold; }\n #hzntalxwue .gt_font_italic { font-style: italic; }\n #hzntalxwue .gt_super { font-size: 65%; }\n #hzntalxwue .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #hzntalxwue .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"5\" class=\"gt_heading gt_title gt_font_normal\" style=\"font-weight: bold;\">Duplicate check — qualtrics_id</td>\n  </tr>\n  <tr class=\"gt_heading\">\n    <td colspan=\"5\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\"></td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">Variable</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"check\">Check</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_flagged\">N Flagged</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pct_flagged\">% Flagged</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pass\">Pass</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td style=\"border-top: 2px solid #333333;\" class=\"gt_row gt_left\">qualtrics_id</td>\n    <td style=\"border-top: 2px solid #333333;\" class=\"gt_row gt_left\">duplicate values</td>\n    <td style=\"border-top: 2px solid #333333;\" class=\"gt_row gt_right\">0</td>\n    <td style=\"border-top: 2px solid #333333;\" class=\"gt_row gt_right\">0.0</td>\n    <td style=\"border-top: 2px solid #333333;\" class=\"gt_row gt_center\">True</td>\n  </tr>\n</tbody>\n\n\n</table>\n\n</div>\n        \n```\n:::\n:::\n\n\n::: {.callout-note}\nNo duplicate student identifiers found. Each of the 1,203 rows corresponds to a unique student.\n:::\n\n### D. Survey response quality\n\nFlag incomplete surveys (`progress` < 100) and outliers in response duration.\n\n::: {#997fe417 .cell execution_count=6}\n``` {.python .cell-code}\nresults = pd.concat([\n    checks.check_range(baseline, \"progress\", 100, 100),\n    checks.check_range(baseline, \"duration_min\", 15, 60),\n])\nutils.gt_check_results(results, title=\"Survey response quality\")\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div id=\"auaisgcsln\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#auaisgcsln table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#auaisgcsln thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#auaisgcsln p { margin: 0; padding: 0; }\n #auaisgcsln .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 16px; font-weight: normal; font-style: normal; background-color: #FFFFFF; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #auaisgcsln .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #auaisgcsln .gt_title { color: #333333; font-size: 125%; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: #FFFFFF; border-bottom-width: 0; }\n #auaisgcsln .gt_subtitle { color: #333333; font-size: 85%; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: #FFFFFF; border-top-width: 0; }\n #auaisgcsln .gt_heading { background-color: #FFFFFF; text-align: center; border-bottom-color: #FFFFFF; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #auaisgcsln .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #auaisgcsln .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #auaisgcsln .gt_col_heading { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #auaisgcsln .gt_column_spanner_outer { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #auaisgcsln .gt_column_spanner_outer:first-child { padding-left: 0; }\n #auaisgcsln .gt_column_spanner_outer:last-child { padding-right: 0; }\n #auaisgcsln .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #auaisgcsln .gt_spanner_row { border-bottom-style: hidden; }\n #auaisgcsln .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #auaisgcsln .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #auaisgcsln .gt_from_md> :first-child { margin-top: 0; }\n #auaisgcsln .gt_from_md> :last-child { margin-bottom: 0; }\n #auaisgcsln .gt_row { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #auaisgcsln .gt_stub { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #auaisgcsln .gt_stub_row_group { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #auaisgcsln .gt_row_group_first td { border-top-width: 2px; }\n #auaisgcsln .gt_row_group_first th { border-top-width: 2px; }\n #auaisgcsln .gt_striped { color: #333333; background-color: #F4F4F4; }\n #auaisgcsln .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #auaisgcsln .gt_grand_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #auaisgcsln .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #auaisgcsln .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #auaisgcsln .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #auaisgcsln .gt_sourcenote { font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #auaisgcsln .gt_left { text-align: left; }\n #auaisgcsln .gt_center { text-align: center; }\n #auaisgcsln .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #auaisgcsln .gt_font_normal { font-weight: normal; }\n #auaisgcsln .gt_font_bold { font-weight: bold; }\n #auaisgcsln .gt_font_italic { font-style: italic; }\n #auaisgcsln .gt_super { font-size: 65%; }\n #auaisgcsln .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #auaisgcsln .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"5\" class=\"gt_heading gt_title gt_font_normal\" style=\"font-weight: bold;\">Survey response quality</td>\n  </tr>\n  <tr class=\"gt_heading\">\n    <td colspan=\"5\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\"></td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">Variable</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"check\">Check</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_flagged\">N Flagged</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pct_flagged\">% Flagged</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pass\">Pass</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td style=\"border-top: 2px solid #333333; background-color: #FDECEA; background-color: #FDECEA;\" class=\"gt_row gt_left\">progress</td>\n    <td style=\"border-top: 2px solid #333333; background-color: #FDECEA; background-color: #FDECEA;\" class=\"gt_row gt_left\">outside [100, 100]</td>\n    <td style=\"border-top: 2px solid #333333; background-color: #FDECEA; background-color: #FDECEA;\" class=\"gt_row gt_right\">23</td>\n    <td style=\"border-top: 2px solid #333333; background-color: #FDECEA; background-color: #FDECEA;\" class=\"gt_row gt_right\">1.9</td>\n    <td style=\"border-top: 2px solid #333333; background-color: #FDECEA; background-color: #FDECEA;\" class=\"gt_row gt_center\">False</td>\n  </tr>\n  <tr>\n    <td style=\"background-color: #FDECEA; background-color: #FDECEA;\" class=\"gt_row gt_left\">duration_min</td>\n    <td style=\"background-color: #FDECEA; background-color: #FDECEA;\" class=\"gt_row gt_left\">outside [15, 60]</td>\n    <td style=\"background-color: #FDECEA; background-color: #FDECEA;\" class=\"gt_row gt_right\">76</td>\n    <td style=\"background-color: #FDECEA; background-color: #FDECEA;\" class=\"gt_row gt_right\">6.3</td>\n    <td style=\"background-color: #FDECEA; background-color: #FDECEA;\" class=\"gt_row gt_center\">False</td>\n  </tr>\n</tbody>\n\n\n</table>\n\n</div>\n        \n```\n:::\n:::\n\n\n::: {.callout-warning}\nTwo response quality issues were identified. First, 23 students (1.9%) did not complete the survey — all stopped between 30–47% progress, suggesting dropout during a specific mid-survey section; their duration (mean: 36.7 min) is comparable to complete surveys (mean: 35.3 min), indicating these were not quick abandons. Second, 76 students (6.3%) fall outside the plausible duration range of 15–60 minutes: 54 completed too quickly (< 15 min, possibly inattentive) and 22 took too long (> 60 min, possibly distracted or interrupted). These students should be flagged as potentially low-quality responses in subsequent analyses.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Incomplete survey detail\n\n::: {#7dfa775e .cell execution_count=7}\n``` {.python .cell-code}\nfrom scipy import stats\n\nincomplete = baseline[baseline[\"progress\"] < 100][[\"progress\", \"duration_min\"]].sort_values(\"progress\")\ncomplete   = baseline[baseline[\"progress\"] == 100][\"duration_min\"]\n\n# Progress at dropout\ncol1 = incomplete[\"progress\"].value_counts().sort_index().reset_index()\ncol1.columns = [\"Progress (%)\", \"N Students\"]\nprint(\"Progress at dropout:\")\nprint(col1.to_string(index=False))\n\n# Duration comparison + t-test\nt_stat, p_val = stats.ttest_ind(incomplete[\"duration_min\"], complete)\ndur_comparison = pd.DataFrame({\n    \"Group\": [\"Incomplete (n=23)\", \"Complete (n=1,180)\"],\n    \"Mean duration (min)\": [\n        round(incomplete[\"duration_min\"].mean(), 1),\n        round(complete.mean(), 1),\n    ],\n    \"SD\": [\n        round(incomplete[\"duration_min\"].std(), 1),\n        round(complete.std(), 1),\n    ],\n})\nprint(\"\\nDuration comparison:\")\nprint(dur_comparison.to_string(index=False))\nprint(f\"\\nt-statistic: {t_stat:.3f}  |  p-value: {p_val:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nProgress at dropout:\n Progress (%)  N Students\n           30           2\n           33           1\n           34           1\n           35           2\n           36           3\n           37           2\n           38           3\n           39           2\n           40           1\n           41           1\n           43           1\n           44           1\n           46           1\n           47           2\n\nDuration comparison:\n             Group  Mean duration (min)   SD\n Incomplete (n=23)                 36.7 11.2\nComplete (n=1,180)                 35.3 11.7\n\nt-statistic: 0.557  |  p-value: 0.578\n```\n:::\n:::\n\n\n:::\n\n::: {#5e8dc487 .cell execution_count=8}\n``` {.python .cell-code}\n# Response quality flags for use in downstream analyses\nbaseline = baseline.copy()\nbaseline[\"flag_incomplete\"] = (baseline[\"progress\"] < 100).astype(int)\nbaseline[\"flag_duration\"]   = ((baseline[\"duration_min\"] < 15) | (baseline[\"duration_min\"] > 60)).astype(int)\nbaseline[\"flag_low_quality\"] = ((baseline[\"flag_incomplete\"] == 1) | (baseline[\"flag_duration\"] == 1)).astype(int)\n\nprint(f\"flag_incomplete:  {baseline['flag_incomplete'].sum()} students\")\nprint(f\"flag_duration:    {baseline['flag_duration'].sum()} students\")\nprint(f\"flag_low_quality: {baseline['flag_low_quality'].sum()} students (union of both)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nflag_incomplete:  23 students\nflag_duration:    76 students\nflag_low_quality: 98 students (union of both)\n```\n:::\n:::\n\n\n### E. Demographics\n\n::: {#af66fddc .cell execution_count=9}\n``` {.python .cell-code}\nresults = pd.concat([\n    checks.check_range(baseline, \"age\", 14, 19),\n    checks.check_consistency(baseline, \"female\", \"male\",\n                              label=\"female + male != 1\"),\n    checks.check_allowed_values(baseline, \"educ_mother\",\n                                 allowed=list(range(1, 11)) + [12]),\n    checks.check_allowed_values(baseline, \"educ_father\",\n                                 allowed=list(range(1, 11)) + [12]),\n    checks.check_binary(baseline, \"has_computer\"),\n    checks.check_binary(baseline, \"has_internet\"),\n    checks.check_range(baseline, \"digital_comfort\", 1, 5),\n    checks.check_range(baseline, \"platform_use\", 1, 4),\n])\nprint(results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       variable                                                  check  n_flagged  pct_flagged  pass\n            age                                       outside [14, 19]          0          0.0  True\n  female / male                                     female + male != 1       1203        100.0 False\n    educ_mother not in allowed set [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12]          0          0.0  True\n    educ_father not in allowed set [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12]          0          0.0  True\n   has_computer                              not in allowed set [0, 1]          0          0.0  True\n   has_internet                              not in allowed set [0, 1]          0          0.0  True\ndigital_comfort                                         outside [1, 5]          2          0.2 False\n   platform_use                                         outside [1, 4]          0          0.0  True\n```\n:::\n:::\n\n\n### L. Academic background and perceptions\n\n::: {#96f5052e .cell execution_count=10}\n``` {.python .cell-code}\nresults = pd.concat([\n    checks.check_range(baseline, \"math_grade_prev\", 1, 4),\n    checks.check_range(baseline, \"like_math\", 1, 5),\n    checks.check_range(baseline, \"like_communication\", 1, 5),\n    checks.check_range(baseline, \"mathconf_learn\", 1, 4),\n    checks.check_range(baseline, \"mathconf_exam\", 1, 4),\n    checks.check_range(baseline, \"mathconf_help_peers\", 1, 4),\n    checks.check_range(baseline, \"mathconf_growth\", 1, 4),\n    checks.check_range(baseline, \"rank_math\", 1, 10),\n    checks.check_range(baseline, \"rank_communication\", 1, 10),\n])\nprint(results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           variable           check  n_flagged  pct_flagged  pass\n    math_grade_prev  outside [1, 4]          0          0.0  True\n          like_math  outside [1, 5]          0          0.0  True\n like_communication  outside [1, 5]          0          0.0  True\n     mathconf_learn  outside [1, 4]          0          0.0  True\n      mathconf_exam  outside [1, 4]          0          0.0  True\nmathconf_help_peers  outside [1, 4]          0          0.0  True\n    mathconf_growth  outside [1, 4]          0          0.0  True\n          rank_math outside [1, 10]          7          0.6 False\n rank_communication outside [1, 10]          0          0.0  True\n```\n:::\n:::\n\n\n### M. Computer lab\n\n::: {#86e0f1db .cell execution_count=11}\n``` {.python .cell-code}\nresults = pd.concat([\n    checks.check_range(baseline, \"lab_productive\", 1, 5),\n    checks.check_range(baseline, \"lab_preferred_hours\", 1, 15),\n])\nprint(results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           variable           check  n_flagged  pct_flagged  pass\n     lab_productive  outside [1, 5]          0          0.0  True\nlab_preferred_hours outside [1, 15]          0          0.0  True\n```\n:::\n:::\n\n\n### G. Hours budget and study habits\n\n::: {#5d78811d .cell execution_count=12}\n``` {.python .cell-code}\nHOURS_COLS = [\"hours_school\", \"hours_study\", \"hours_friends\", \"hours_entertainment\",\n              \"hours_housework\", \"hours_unpaid_work\", \"hours_paid_work\",\n              \"hours_sleep\", \"hours_sport\"]\n\nhours_results = checks.check_hours_budget(\n    baseline,\n    hours_cols=HOURS_COLS,\n    min_total=10,\n    max_total=30,\n    zero_exempt=[\"hours_unpaid_work\", \"hours_paid_work\"],\n    high_threshold=12,\n)\n\nprint(\"--- Budget ---\")\nprint(hours_results[\"budget\"].to_string(index=False))\nprint(\"\\n--- Unexpected zeroes ---\")\nprint(hours_results[\"zeroes\"].to_string(index=False))\nprint(\"\\n--- Abnormally high values ---\")\nprint(hours_results[\"high_values\"].to_string(index=False))\n\n# Study habit variables\nstudy_results = pd.concat([\n    checks.check_range(baseline, \"math_study_weekly\", 1, 5),\n    checks.check_range(baseline, \"study_context\", 1, 4),\n    checks.check_range(baseline, \"digital_tools_used\", 1, 5),\n])\nprint(\"\\n--- Study habits ---\")\nprint(study_results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n--- Budget ---\n                             check  n_flagged  pct_flagged  pass\ndaily hours total outside [10, 30]         98          8.1 False\n\n--- Unexpected zeroes ---\n           variable  n_zero  pct_zero\n        hours_sport     214      17.8\n    hours_housework      89       7.4\n      hours_friends      56       4.7\n        hours_study      46       3.8\nhours_entertainment      34       2.8\n       hours_school       0       0.0\n        hours_sleep       0       0.0\n\n--- Abnormally high values ---\n           variable  threshold  n_flagged  pct_flagged\n        hours_study         12         38          3.2\n       hours_school         12          0          0.0\n      hours_friends         12          0          0.0\nhours_entertainment         12          0          0.0\n    hours_housework         12          0          0.0\n  hours_unpaid_work         12          0          0.0\n    hours_paid_work         12          0          0.0\n        hours_sleep         12          0          0.0\n        hours_sport         12          0          0.0\n\n--- Study habits ---\n          variable          check  n_flagged  pct_flagged  pass\n math_study_weekly outside [1, 5]          0          0.0  True\n     study_context outside [1, 4]          0          0.0  True\ndigital_tools_used outside [1, 5]          0          0.0  True\n```\n:::\n:::\n\n\n### F. Scale validity\n\nRange checks on all items and replication of pre-computed averages. Reversal checks applied where items are reverse-coded.\n\n::: {#d7c2eecf .cell execution_count=13}\n``` {.python .cell-code}\n# ── Grit (1–5; grit_quit_game and grit_lose_interest reversed) ───────────────\ngrit_items = [\"grit_challenge\", \"grit_quit_game\", \"grit_lose_interest\", \"grit_hardwork\"]\nresults = pd.concat([\n    *[checks.check_range(baseline, c, 1, 5) for c in grit_items],\n    checks.check_range(baseline, \"grit_avg\", 1, 5),\n    checks.check_reversal(baseline,\n                          direct_items=[\"grit_challenge\", \"grit_hardwork\"],\n                          reversed_items=[\"grit_quit_game\", \"grit_lose_interest\"],\n                          avg_col=\"grit_avg\", scale_max=5),\n])\nprint(\"Grit\\n\", results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGrit\n           variable             check  n_flagged  pct_flagged pass  naive_match_pct  reversed_match_pct       conclusion\n    grit_challenge    outside [1, 5]        0.0          0.0 True              NaN                 NaN              NaN\n    grit_quit_game    outside [1, 5]        0.0          0.0 True              NaN                 NaN              NaN\ngrit_lose_interest    outside [1, 5]        0.0          0.0 True              NaN                 NaN              NaN\n     grit_hardwork    outside [1, 5]        0.0          0.0 True              NaN                 NaN              NaN\n          grit_avg    outside [1, 5]        0.0          0.0 True              NaN                 NaN              NaN\n          grit_avg reversal applied?        NaN          NaN  NaN             19.9               100.0 reversal applied\n```\n:::\n:::\n\n\n::: {#38c62e15 .cell execution_count=14}\n``` {.python .cell-code}\n# ── Growth mindset (1–6) ──────────────────────────────────────────────────────\nmindset_items = [\"mindset_fixed1\", \"mindset_fixed2\"]\nresults = pd.concat([\n    *[checks.check_range(baseline, c, 1, 6) for c in mindset_items],\n    checks.check_range(baseline, \"mindset_avg\", 1, 6),\n    checks.check_avg_replication(baseline, mindset_items, \"mindset_avg\"),\n])\nprint(\"Growth mindset\\n\", results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGrowth mindset\n       variable                                  check  n_flagged  pct_flagged  pass\nmindset_fixed1                         outside [1, 6]          0          0.0  True\nmindset_fixed2                         outside [1, 6]          0          0.0  True\n   mindset_avg                         outside [1, 6]          0          0.0  True\n   mindset_avg computed avg != mindset_avg (tol=0.01)       1013         84.2 False\n```\n:::\n:::\n\n\n::: {#f20dbdbd .cell execution_count=15}\n``` {.python .cell-code}\n# ── Locus of control (1–5) ────────────────────────────────────────────────────\nlocus_items = [\"locus_luck\", \"locus_fate\", \"locus_prepared\", \"locus_plans\"]\nresults = pd.concat([\n    *[checks.check_range(baseline, c, 1, 5) for c in locus_items],\n    checks.check_range(baseline, \"locus_avg\", 1, 5),\n    checks.check_avg_replication(baseline, locus_items, \"locus_avg\"),\n])\nprint(\"Locus of control\\n\", results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLocus of control\n       variable                                check  n_flagged  pct_flagged  pass\n    locus_luck                       outside [1, 5]          0          0.0  True\n    locus_fate                       outside [1, 5]          0          0.0  True\nlocus_prepared                       outside [1, 5]          0          0.0  True\n   locus_plans                       outside [1, 5]          0          0.0  True\n     locus_avg                       outside [1, 5]          0          0.0  True\n     locus_avg computed avg != locus_avg (tol=0.01)        958         79.6 False\n```\n:::\n:::\n\n\n::: {#9929c06c .cell execution_count=16}\n``` {.python .cell-code}\n# ── Self-efficacy (1–4) ───────────────────────────────────────────────────────\nefficacy_items = [\"efficacy_hard_problems\", \"efficacy_effort\", \"efficacy_calm\",\n                   \"efficacy_solutions\", \"efficacy_trouble\"]\nresults = pd.concat([\n    *[checks.check_range(baseline, c, 1, 4) for c in efficacy_items],\n    checks.check_range(baseline, \"efficacy_avg\", 1, 4),\n    checks.check_avg_replication(baseline, efficacy_items, \"efficacy_avg\"),\n])\nprint(\"Self-efficacy\\n\", results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSelf-efficacy\n               variable                                   check  n_flagged  pct_flagged  pass\nefficacy_hard_problems                          outside [1, 4]          0          0.0  True\n       efficacy_effort                          outside [1, 4]          0          0.0  True\n         efficacy_calm                          outside [1, 4]          0          0.0  True\n    efficacy_solutions                          outside [1, 4]          0          0.0  True\n      efficacy_trouble                          outside [1, 4]          0          0.0  True\n          efficacy_avg                          outside [1, 4]          0          0.0  True\n          efficacy_avg computed avg != efficacy_avg (tol=0.01)          0          0.0  True\n```\n:::\n:::\n\n\n::: {#f3c05cc1 .cell execution_count=17}\n``` {.python .cell-code}\n# ── Math enjoyment (1–5; math_wish_no reversed) ───────────────────────────────\nresults = pd.concat([\n    *[checks.check_range(baseline, c, 1, 5)\n      for c in [\"math_enjoy\", \"math_wish_no\", \"math_like_problems\"]],\n    checks.check_range(baseline, \"math_enjoy_avg\", 1, 5),\n    checks.check_reversal(baseline,\n                          direct_items=[\"math_enjoy\", \"math_like_problems\"],\n                          reversed_items=[\"math_wish_no\"],\n                          avg_col=\"math_enjoy_avg\", scale_max=5),\n])\nprint(\"Math enjoyment\\n\", results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMath enjoyment\n           variable             check  n_flagged  pct_flagged pass  naive_match_pct  reversed_match_pct       conclusion\n        math_enjoy    outside [1, 5]        0.0          0.0 True              NaN                 NaN              NaN\n      math_wish_no    outside [1, 5]        0.0          0.0 True              NaN                 NaN              NaN\nmath_like_problems    outside [1, 5]        0.0          0.0 True              NaN                 NaN              NaN\n    math_enjoy_avg    outside [1, 5]        0.0          0.0 True              NaN                 NaN              NaN\n    math_enjoy_avg reversal applied?        NaN          NaN  NaN             19.9               100.0 reversal applied\n```\n:::\n:::\n\n\n::: {#6a13f7f3 .cell execution_count=18}\n``` {.python .cell-code}\n# ── Math anxiety (1–5) ────────────────────────────────────────────────────────\nresults = pd.concat([\n    checks.check_range(baseline, \"math_worry_grades\", 1, 5),\n    checks.check_range(baseline, \"math_nervous_exams\", 1, 5),\n    checks.check_range(baseline, \"math_anxiety_avg\", 1, 5),\n    checks.check_avg_replication(baseline,\n                                  [\"math_worry_grades\", \"math_nervous_exams\"],\n                                  \"math_anxiety_avg\"),\n])\nprint(\"Math anxiety\\n\", results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMath anxiety\n           variable                                       check  n_flagged  pct_flagged  pass\n math_worry_grades                              outside [1, 5]          0          0.0  True\nmath_nervous_exams                              outside [1, 5]          0          0.0  True\n  math_anxiety_avg                              outside [1, 5]          0          0.0  True\n  math_anxiety_avg computed avg != math_anxiety_avg (tol=0.01)          0          0.0  True\n```\n:::\n:::\n\n\n::: {#dde6f0b9 .cell execution_count=19}\n``` {.python .cell-code}\n# ── Math self-concept (1–5; math_harder_than_peers reversed) ─────────────────\nresults = pd.concat([\n    checks.check_range(baseline, \"math_does_well\", 1, 5),\n    checks.check_range(baseline, \"math_harder_than_peers\", 1, 5),\n    checks.check_range(baseline, \"math_selfconcept_avg\", 1, 5),\n    checks.check_reversal(baseline,\n                          direct_items=[\"math_does_well\"],\n                          reversed_items=[\"math_harder_than_peers\"],\n                          avg_col=\"math_selfconcept_avg\", scale_max=5),\n])\nprint(\"Math self-concept\\n\", results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMath self-concept\n               variable             check  n_flagged  pct_flagged pass  naive_match_pct  reversed_match_pct       conclusion\n        math_does_well    outside [1, 5]        0.0          0.0 True              NaN                 NaN              NaN\nmath_harder_than_peers    outside [1, 5]        0.0          0.0 True              NaN                 NaN              NaN\n  math_selfconcept_avg    outside [1, 5]        0.0          0.0 True              NaN                 NaN              NaN\n  math_selfconcept_avg reversal applied?        NaN          NaN  NaN             19.5               100.0 reversal applied\n```\n:::\n:::\n\n\n::: {#8d82978d .cell execution_count=20}\n``` {.python .cell-code}\n# ── Math attitudes standalone (math_useful: 1–4) ─────────────────────────────\nprint(\"Math attitudes\\n\",\n      checks.check_range(baseline, \"math_useful\", 1, 4).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMath attitudes\n    variable          check  n_flagged  pct_flagged  pass\nmath_useful outside [1, 4]          0          0.0  True\n```\n:::\n:::\n\n\n::: {#9413a254 .cell execution_count=21}\n``` {.python .cell-code}\n# ── Belonging (1–5) ───────────────────────────────────────────────────────────\nresults = pd.concat([\n    checks.check_range(baseline, \"belong_outsider\", 1, 5),\n    checks.check_range(baseline, \"belong_fits_in\", 1, 5),\n    checks.check_range(baseline, \"belonging_avg\", 1, 5),\n    checks.check_avg_replication(baseline,\n                                  [\"belong_outsider\", \"belong_fits_in\"],\n                                  \"belonging_avg\"),\n])\nprint(\"Belonging\\n\", results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBelonging\n        variable                                    check  n_flagged  pct_flagged  pass\nbelong_outsider                           outside [1, 5]          0          0.0  True\n belong_fits_in                           outside [1, 5]          0          0.0  True\n  belonging_avg                           outside [1, 5]          0          0.0  True\n  belonging_avg computed avg != belonging_avg (tol=0.01)        967         80.4 False\n```\n:::\n:::\n\n\n::: {#f974b15c .cell execution_count=22}\n``` {.python .cell-code}\n# ── Metacognition ─────────────────────────────────────────────────────────────\nmeta_1_4 = [\"meta_study_allocation\", \"meta_when_stuck\", \"meta_hint_use\",\n             \"meta_review_errors\", \"meta_after_mistake\", \"meta_ai_use\"]\nresults = pd.concat([\n    *[checks.check_range(baseline, c, 1, 4) for c in meta_1_4],\n    checks.check_range(baseline, \"meta_expected_exam\", 1, 5),\n    checks.check_range(baseline, \"meta_actual_exam\", 1, 5),\n    checks.check_range(baseline, \"meta_self_awareness\", 1, 3),\n])\nprint(\"Metacognition\\n\", results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMetacognition\n              variable          check  n_flagged  pct_flagged  pass\nmeta_study_allocation outside [1, 4]          0          0.0  True\n      meta_when_stuck outside [1, 4]          0          0.0  True\n        meta_hint_use outside [1, 4]          0          0.0  True\n   meta_review_errors outside [1, 4]          0          0.0  True\n   meta_after_mistake outside [1, 4]          0          0.0  True\n          meta_ai_use outside [1, 4]          0          0.0  True\n   meta_expected_exam outside [1, 5]          0          0.0  True\n     meta_actual_exam outside [1, 5]          0          0.0  True\n  meta_self_awareness outside [1, 3]          0          0.0  True\n```\n:::\n:::\n\n\n::: {#f8afee4e .cell execution_count=23}\n``` {.python .cell-code}\n# ── Barriers (1–5) ────────────────────────────────────────────────────────────\nbarrier_cols = [\"barrier_money\", \"barrier_work_family\", \"barrier_parent_ideas\",\n                \"barrier_grades\", \"barrier_info_careers\", \"barrier_info_institution\",\n                \"barrier_family_resp\"]\nresults = pd.concat([checks.check_range(baseline, c, 1, 5) for c in barrier_cols])\nprint(\"Barriers\\n\", results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBarriers\n                 variable          check  n_flagged  pct_flagged  pass\n           barrier_money outside [1, 5]          0          0.0  True\n     barrier_work_family outside [1, 5]          0          0.0  True\n    barrier_parent_ideas outside [1, 5]          0          0.0  True\n          barrier_grades outside [1, 5]          0          0.0  True\n    barrier_info_careers outside [1, 5]          0          0.0  True\nbarrier_info_institution outside [1, 5]          0          0.0  True\n     barrier_family_resp outside [1, 5]          0          0.0  True\n```\n:::\n:::\n\n\n::: {#f9d06fa5 .cell execution_count=24}\n``` {.python .cell-code}\n# ── Knowledge of opportunities (1–3) ─────────────────────────────────────────\nresults = pd.concat([\n    checks.check_range(baseline, \"knows_scholarship\", 1, 3),\n    checks.check_range(baseline, \"knows_beca18\", 1, 3),\n    checks.check_range(baseline, \"knows_alt_training\", 1, 3),\n])\nprint(\"Knowledge of opportunities\\n\", results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nKnowledge of opportunities\n           variable          check  n_flagged  pct_flagged  pass\n knows_scholarship outside [1, 3]          0          0.0  True\n      knows_beca18 outside [1, 3]          0          0.0  True\nknows_alt_training outside [1, 3]          0          0.0  True\n```\n:::\n:::\n\n\n### N. Aspirations\n\n::: {#32c49a2d .cell execution_count=25}\n``` {.python .cell-code}\nresults = pd.concat([\n    checks.check_range(baseline, \"barrier_finish_school\", 1, 2),\n    checks.check_range(baseline, \"info_postsecondary\", 1, 5),\n    checks.check_range(baseline, \"plan_after_school\", 1, 5),\n    checks.check_range(baseline, \"plan_feasibility\", 1, 5),\n    checks.check_range(baseline, \"knows_career\", 1, 3),\n    checks.check_range(baseline, \"parent_educ_expectation\", 1, 4),\n    checks.check_binary(baseline, \"enrolled_academy\"),\n    checks.check_range(baseline, \"belief_univ_transition\", 0, 10),\n])\nprint(results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               variable                     check  n_flagged  pct_flagged  pass\n  barrier_finish_school            outside [1, 2]          0          0.0  True\n     info_postsecondary            outside [1, 5]          0          0.0  True\n      plan_after_school            outside [1, 5]          0          0.0  True\n       plan_feasibility            outside [1, 5]          0          0.0  True\n           knows_career            outside [1, 3]          0          0.0  True\nparent_educ_expectation            outside [1, 4]          0          0.0  True\n       enrolled_academy not in allowed set [0, 1]          0          0.0  True\n belief_univ_transition           outside [0, 10]          5          0.4 False\n```\n:::\n:::\n\n\n### O. Social network\n\n::: {#b59d5187 .cell execution_count=26}\n``` {.python .cell-code}\nfriend_cols = [f\"friend{i}_{var}\"\n               for i in range(1, 6)\n               for var in [\"recess\", \"homework\", \"future_talk\", \"whatsapp\"]]\n\nresults = pd.concat([\n    checks.check_range(baseline, \"num_close_friends\", 1, 6),\n    *[checks.check_binary(baseline, c) for c in friend_cols if c in baseline.columns],\n])\nprint(results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           variable                     check  n_flagged  pct_flagged  pass\n  num_close_friends            outside [1, 6]          0          0.0  True\n     friend1_recess not in allowed set [0, 1]          0          0.0  True\n   friend1_homework not in allowed set [0, 1]          0          0.0  True\nfriend1_future_talk not in allowed set [0, 1]          0          0.0  True\n   friend1_whatsapp not in allowed set [0, 1]          0          0.0  True\n     friend2_recess not in allowed set [0, 1]          0          0.0  True\n   friend2_homework not in allowed set [0, 1]          0          0.0  True\nfriend2_future_talk not in allowed set [0, 1]          0          0.0  True\n   friend2_whatsapp not in allowed set [0, 1]          0          0.0  True\n     friend3_recess not in allowed set [0, 1]          0          0.0  True\n   friend3_homework not in allowed set [0, 1]          0          0.0  True\nfriend3_future_talk not in allowed set [0, 1]          0          0.0  True\n   friend3_whatsapp not in allowed set [0, 1]          0          0.0  True\n     friend4_recess not in allowed set [0, 1]          0          0.0  True\n   friend4_homework not in allowed set [0, 1]          0          0.0  True\nfriend4_future_talk not in allowed set [0, 1]          0          0.0  True\n   friend4_whatsapp not in allowed set [0, 1]          0          0.0  True\n     friend5_recess not in allowed set [0, 1]          0          0.0  True\n   friend5_homework not in allowed set [0, 1]          0          0.0  True\nfriend5_future_talk not in allowed set [0, 1]          0          0.0  True\n   friend5_whatsapp not in allowed set [0, 1]          0          0.0  True\n```\n:::\n:::\n\n\n### I. Salary beliefs\n\n::: {#5044cb0e .cell execution_count=27}\n``` {.python .cell-code}\nresults = pd.concat([\n    checks.check_range(baseline, \"salary_secondary\", 1, 50000),\n    checks.check_range(baseline, \"salary_technical\", 1, 50000),\n    checks.check_range(baseline, \"salary_university\", 1, 50000),\n    checks.check_ordering(baseline,\n                          cols=[\"salary_secondary\", \"salary_technical\", \"salary_university\"],\n                          label=\"salary ordering violated (secondary <= technical <= university)\"),\n])\nprint(results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                               variable                                                           check  n_flagged  pct_flagged  pass\n                                       salary_secondary                                              outside [1, 50000]         20          1.7 False\n                                       salary_technical                                              outside [1, 50000]          0          0.0  True\n                                      salary_university                                              outside [1, 50000]          2          0.2 False\nsalary_secondary / salary_technical / salary_university salary ordering violated (secondary <= technical <= university)        550         45.7 False\n```\n:::\n:::\n\n\n### H. Math assessment consistency\n\n::: {#925a1fe1 .cell execution_count=28}\n``` {.python .cell-code}\ncorrect_cols = [\"correct_a1\", \"correct_a2\", \"correct_a7\", \"correct_a8\", \"correct_a8m\",\n                \"correct_a4\", \"correct_a9s\", \"correct_a3\", \"correct_a6\", \"correct_a5\"]\n\nresults = pd.concat([\n    *[checks.check_binary(baseline, c) for c in correct_cols],\n    checks.check_derived(\n        baseline, \"score_total_baseline\",\n        formula_fn=lambda df: df[correct_cols].sum(axis=1),\n        label=\"score_total != sum of correct_a* items\",\n    ),\n    checks.check_derived(\n        baseline, \"score_pct_baseline\",\n        formula_fn=lambda df: df[\"score_total_baseline\"] / 10,\n        label=\"score_pct != score_total / 10\",\n    ),\n])\nprint(results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            variable                                  check  n_flagged  pct_flagged  pass\n          correct_a1              not in allowed set [0, 1]          0          0.0  True\n          correct_a2              not in allowed set [0, 1]          0          0.0  True\n          correct_a7              not in allowed set [0, 1]          0          0.0  True\n          correct_a8              not in allowed set [0, 1]          0          0.0  True\n         correct_a8m              not in allowed set [0, 1]          0          0.0  True\n          correct_a4              not in allowed set [0, 1]          0          0.0  True\n         correct_a9s              not in allowed set [0, 1]          0          0.0  True\n          correct_a3              not in allowed set [0, 1]          0          0.0  True\n          correct_a6              not in allowed set [0, 1]          0          0.0  True\n          correct_a5              not in allowed set [0, 1]          0          0.0  True\nscore_total_baseline score_total != sum of correct_a* items          0          0.0  True\n  score_pct_baseline          score_pct != score_total / 10          0          0.0  True\n```\n:::\n:::\n\n\n### J. Derived variable consistency\n\n::: {#c00efe90 .cell execution_count=29}\n``` {.python .cell-code}\nresults = pd.concat([\n    checks.check_derived(\n        baseline, \"educ_parent_max\",\n        formula_fn=lambda df: df[[\"educ_mother\", \"educ_father\"]].max(axis=1),\n        label=\"educ_parent_max != max(educ_mother, educ_father)\",\n    ),\n])\nprint(results.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       variable                                            check  n_flagged  pct_flagged  pass\neduc_parent_max educ_parent_max != max(educ_mother, educ_father)          0          0.0  True\n```\n:::\n:::\n\n\n",
    "supporting": [
      "01_data_quality_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}